name: pushing

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set default home to Contents
        run: sed -i 's/:default-home {:page "Journals"}/:default-home {:page "Contents"}/' $GITHUB_WORKSPACE/logseq/config.edn
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@v0.1
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: www # The folder the action should deploy.
          clean: true
